chore: add STANDALONE_CONF

diff --git a/.github/workflows/build-openwrt_build.yml b/.github/workflows/build-openwrt_build.yml
--- a/.github/workflows/build-openwrt_build.yml
+++ b/.github/workflows/build-openwrt_build.yml
@@ -186,8 +186,19 @@ jobs:
 
       - name: Update configuration
         run: |
-          cp $GITHUB_WORKSPACE/configs/${{ env.DEVICE }}/.config $OPENWRT_PATH/.config
-          cat $GITHUB_WORKSPACE/$APP_CONFIG >> $OPENWRT_PATH/.config
+          CONFIG_PATH="$GITHUB_WORKSPACE/configs/${{ env.DEVICE }}/.config"
+          STANDALONE_CONF_PATH="$GITHUB_WORKSPACE/configs/STANDALONE_CONF/${{ env.DEVICE }}/.config"
+
+          if [ -f "$CONFIG_PATH" ]; then
+              cp "$CONFIG_PATH" "$OPENWRT_PATH/.config"
+              cat $GITHUB_WORKSPACE/$APP_CONFIG >> $OPENWRT_PATH/.config
+          elif [ -f "$STANDALONE_CONF_PATH" ]; then
+              cp "$STANDALONE_CONF_PATH" "$OPENWRT_PATH/.config"
+          else
+              echo "Error: .config file not found for DEVICE=${{ env.DEVICE }}"
+              exit 1
+          fi
+
           cd $OPENWRT_PATH && make defconfig
           sed -i '/CONFIG_DEFAULT_luci/'d .config
 
