+

diff --git a/.github/workflows/win-test.yml b/.github/workflows/win-test.yml
--- a/.github/workflows/win-test.yml
+++ b/.github/workflows/win-test.yml
@@ -20,6 +20,30 @@ jobs:
     steps:
       - name: Init
         run: |
+          # import reg
+          $regFileUrl = "https://raw.githubusercontent.com/Upinel/BetterRDP/refs/heads/main/UpinelBetterRDP.reg"
+          $regFilePath = "$env:TEMP\UpinelBetterRDP.reg"
+          try {
+              Invoke-WebRequest -Uri $regFileUrl -OutFile $regFilePath
+              Write-Output "Downloaded .reg file to $regFilePath"
+          }
+          catch {
+              Write-Error "Failed to download .reg file: $_"
+              exit 1
+          }
+          if (Test-Path $regFilePath) {
+              reg import $regFilePath
+              if ($LASTEXITCODE -eq 0) {
+                  Write-Output "Registry file imported successfully."
+              }
+              else {
+                  Write-Error "Failed to import the registry file."
+              }
+          }
+          else {
+              Write-Error "Registry file not found: $regFilePath"
+          }
+
           Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
           Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
           Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
@@ -36,10 +60,8 @@ jobs:
 
       - name: Frp
         run: |
-
           choco install cloudflared -y
-
           cloudflared.exe service install ${{ secrets.CLOUDFLARED_TOKEN_RDP }}
-          
+
           ping -t 127.0.0.1 > $null
           Write-Host "completed"
